//Create a website to display a joke each time website is refreshed fethed from an array of 100 jokes

const jokes = [
  "Why don't scientists trust atoms? Because they make up everything!",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "Why don’t skeletons fight each other? They don’t have the guts.",
  "What do you call fake spaghetti? An impasta!",
  "Why did the bicycle fall over? Because it was two-tired!",
  "What did one wall say to the other wall? I'll meet you at the corner!",
  "Why do cows wear bells? Because their horns don’t work!",
  "What do you get when you cross a snowman and a vampire? Frostbite!",
  "Why couldn’t the leopard hide? Because he was always spotted!",
  "What do you call cheese that isn't yours? Nacho cheese!",
  "Why did the golfer bring an extra pair of pants? In case he got a hole in one!",
  "What kind of shoes do ninjas wear? Sneakers!",
  "Why was the math book sad? It had too many problems!",
  "Why did the tomato blush? Because it saw the salad dressing!",
  "What’s orange and sounds like a parrot? A carrot!",
  "Why don’t eggs tell jokes? They might crack up!",
  "Why did the chicken go to the séance? To talk to the other side!",
  "How do you organize a space party? You planet!",
  "Why do bees have sticky hair? Because they use honeycombs!",
  "What did one ocean say to the other ocean? Nothing, they just waved!",
  "What did the grape do when he got stepped on? Nothing but let out a little whine!",
  "Why do melons have weddings? Because they cantaloupe!",
  "What did the janitor say when he jumped out of the closet? Supplies!",
  "Why do we never tell secrets on a farm? Because the potatoes have eyes and the corn has ears!",
  "What did one hat say to the other? You stay here, I’ll go on ahead!",
  "Why did the belt get arrested? Because it held up a pair of pants!",
  "What do you call an alligator in a vest? An investigator!",
  "Why do birds fly south in the winter? Because it's too far to walk!",
  "What do you call a sleeping bull? A bulldozer!",
  "Why are elevator jokes so good? They work on many levels!",
  "What did one plate say to the other? Lunch is on me!",
  "How does a penguin build its house? Igloos it together!",
  "What do you call a bear with no teeth? A gummy bear!",
  "Why do seagulls fly over the ocean? Because if they flew over the bay, they’d be bagels!",
  "Why don’t some fish play piano? Because you can’t tuna fish!",
  "Why was the calendar so popular? It had lots of dates!",
  "Why couldn’t the pony sing a lullaby? He was a little horse!",
  "Why are ghosts bad liars? Because you can see right through them!",
  "Why did the frog take the bus to work? His car was toad!",
  "What kind of music do mummies listen to? Wrap music!",
  "What do you call an elephant that doesn’t matter? An irrelephant!",
  "Why did the coffee file a police report? It got mugged!",
  "Why do dads tell such bad jokes? They want to make a pun impression!",
  "Why don’t skeletons like parties? They have no body to dance with!",
  "What do you call a pile of cats? A meowtain!",
  "Why are frogs so happy? They eat whatever bugs them!",
  "What do you call a cow with no legs? Ground beef!",
  "What happens when a snowman throws a tantrum? He has a meltdown!",
  "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
  "Why did the scarecrow become a motivational speaker? He was outstanding in his field!",
  "What’s brown and sticky? A stick!",
  "Why did the barber win the race? He knew all the short cuts!",
  "How do you catch a squirrel? Climb a tree and act like a nut!",
  "What did the zero say to the eight? Nice belt!",
  "Why did the banana go to the doctor? It wasn’t peeling well!",
  "Why don’t oysters share their pearls? Because they’re shellfish!",
  "What do you get when you cross a fish and an elephant? Swimming trunks!",
  "Why did the banana break up with the orange? It found him unpeeling!",
  "Why did the chicken sit at the computer? To browse the web!",
  "Why was the broom late? It swept in!",
  "What’s a vampire’s favorite fruit? A necktarine!",
  "What did one traffic light say to the other? Stop looking, I’m changing!",
  "Why did the musician get locked out of his house? He broke a key!",
  "What do you call a factory that makes good products? A satisfactory!",
  "What do you call a dog magician? A labracadabrador!",
  "What do you call an illegally parked frog? Toad!",
  "Why don’t mountains get tired? They peak all the time!",
  "What did the buffalo say to his son? Bison!",
  "Why was Cinderella so bad at soccer? She kept running away from the ball!",
  "What do you call a pig that knows karate? A pork chop!",
  "How do you organize a haunted house party? You ghost it!",
  "Why don’t trees use social media? They don’t want to be logged in!"
];


let joke = jokes[Math.floor(Math.random() * jokes.length)];

let a = document.getElementById("joke");
a.innerHTML = joke;

